from fpdf import FPDF

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)

# Title Page
pdf.add_page()
pdf.set_font('Helvetica', 'B', 28)
pdf.set_text_color(102, 126, 234)
pdf.ln(50)
pdf.cell(0, 15, 'AAVA', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.set_font('Helvetica', '', 16)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 10, 'Authorised Address Validation Agency', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(10)
pdf.set_font('Helvetica', 'I', 12)
pdf.set_text_color(128, 128, 128)
pdf.cell(0, 8, 'Part of DHRUVA Digital Address Ecosystem', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.cell(0, 8, 'Government of India Initiative - Department of Posts', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(50)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(128, 128, 128)
pdf.cell(0, 8, 'Documentation Version 1.0 - November 30, 2025', new_x="LMARGIN", new_y="NEXT", align='C')

# Overview
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '1. Overview', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "AAVA (Authorised Address Validation Agency) is a comprehensive web application. It is part of India's DHRUVA Digital Address Ecosystem - a Government of India initiative by the Department of Posts.\n\nThe application provides a unified digital addressing system with address validation, DIGIPIN geocoding, confidence scoring, and AI-powered assistance.")

# Problem Statement
pdf.ln(5)
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '2. Problem Statement', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "India faces critical addressing challenges:\n\n- 60-80 million households lack formal addresses\n- Rural areas have ambiguous landmark-based addresses\n- Urban slums/informal settlements excluded from formal systems\n- No standardized digital addressing infrastructure\n- Delivery failures cost the economy billions annually")

# DHRUVA Ecosystem
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '3. DHRUVA Ecosystem', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "DHRUVA = Digital Hyperlocal Unique Reliable Verified Address\n\nA unified national digital addressing system with 4 core pillars:\n\n- DIGIPIN: Digital Postal Index Number - 10-character geocode system\n- DARPAN: Digital Address Repository for Precision Addressing Network\n- DIVYA: Digital Interface for Verified and Yielded Addresses\n- AAVA: Authorised Address Validation Agency - Quality assurance")

pdf.ln(5)
pdf.set_font('Helvetica', 'B', 12)
pdf.cell(0, 8, 'Ecosystem Participants:', new_x="LMARGIN", new_y="NEXT")
pdf.set_font('Helvetica', '', 11)
pdf.multi_cell(0, 7, "- CM (Central Mapper): Maintains DIGIPIN grid system\n- AIP (Address Information Provider): Creates/updates addresses\n- AIA (Address Information Agent): Field agents who verify\n- AIU (Address Information User): Consumers of address data\n- AAVA: Validates address accuracy")

# Technology Stack
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '4. Technology Stack', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "- Frontend: Streamlit (Python)\n- Backend: Python 3.8+\n- Database: SQLite\n- Maps: Folium + Streamlit-Folium\n- Charts: Plotly Express\n- AI Chat: Google Gemini API\n\nKey Dependencies:\n- streamlit, pandas, numpy, plotly\n- folium, streamlit-folium\n- google-generativeai, python-dotenv\n- Pillow, python-dateutil")

# Project Structure
pdf.ln(10)
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '5. Project Structure', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Main Files:\n- app.py: Main application\n- requirements.txt: Dependencies\n- .env: API keys\n\nPages:\n- Validation Request, Agent Portal\n- Confidence Score, Admin Panel, AI Chat\n\nUtils:\n- database.py, digipin.py, confidence_score.py")

# Application Pages
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '6. Application Pages', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Home (Dashboard): System overview with metrics\n\nValidation Request: Submit address validation requests with DIGIPIN\n\nAgent Portal: Agent authentication, task management, GPS capture\n\nConfidence Score: Calculate and analyze scores (A+ to F grades)\n\nAdmin Panel: System administration, audit logs, reports\n\nAI Chat: General-purpose AI assistant with AAVA expertise")

# DIGIPIN Specifications
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '7. DIGIPIN Technical Specifications', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "DIGIPIN is a 10-character alphanumeric geocode that pinpoints any location in India to approximately 4m x 4m accuracy.\n\nCharacter Set (16 chars): 2 3 4 5 6 7 8 9 C F J K L M P T\n\nGeographic Bounds:\n- Latitude: 2.5N to 38.5N\n- Longitude: 63.5E to 99.5E\n\nResolution:\n- Level 1: ~1000 km\n- Level 5: ~4 km\n- Level 10: ~4 m (exact spot)\n\nFormat:\n- Raw: 3PJK4M5L2T\n- Display: 3PJ-K4M-5L2T")

# Confidence Score
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '8. Confidence Score Algorithm', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Formula: SCORE = 100 x [(DSR x 0.30) + (SC x 0.30) + (TF x 0.20) + (PVS x 0.20)]\n\nComponents:\n1. DSR (Delivery Success Rate) - 30%\n2. SC (Spatial Consistency) - 30%\n3. TF (Temporal Freshness) - 20%\n4. PVS (Physical Verification Status) - 20%\n\nGrade Thresholds:\n- A+ (90-100): Excellent\n- A (80-89): Very Good\n- B (70-79): Good\n- C (60-69): Fair\n- D (50-59): Poor\n- F (0-49): Fail")

# Database
pdf.ln(10)
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '9. Database Schema', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "7 Core Tables:\n1. addresses - DIGIPIN, coordinates, scores\n2. validations - Status tracking\n3. agents - Performance metrics\n4. deliveries - DSR calculation\n5. verifications - Evidence records\n6. consents - Privacy compliance\n7. audit_logs - Hash-chained logs")

# Installation
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '10. Installation & Setup', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Prerequisites: Python 3.8+, pip, Git\n\nSteps:\n1. git clone https://github.com/Razz0711/AAVA.git\n2. cd AAVA\n3. python -m venv venv\n4. venv\\Scripts\\activate (Windows)\n5. pip install -r requirements.txt\n6. Create .env with GEMINI_API_KEY\n7. streamlit run app.py\n8. Open http://localhost:8501")

# Deployment
pdf.ln(10)
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '11. Deployment', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Streamlit Cloud:\n1. Push to GitHub\n2. Connect at share.streamlit.io\n3. Add GEMINI_API_KEY in secrets\n4. Deploy\n\nLive URL: https://aava-app.streamlit.app")

# AI Chat
pdf.add_page()
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '12. AI Chat Features', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Capabilities:\n- General Purpose AI (any topic)\n- Academic Help (syllabus, homework)\n- AAVA Expertise (DIGIPIN, scores)\n- Coding Help (any language)\n\nCommands:\n- encode 28.6139, 77.2090\n- decode 3PJK4M5L2T\n- validate 3PJ-K4M-5L2T\n- show stats\n\nFeatures:\n- Multiple chat sessions\n- 48-hour auto-delete\n- Persistent memory")

# Security & Compliance
pdf.ln(10)
pdf.set_font('Helvetica', 'B', 16)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 10, '13. Security & Compliance', new_x="LMARGIN", new_y="NEXT")
pdf.ln(5)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(0, 0, 0)
pdf.multi_cell(0, 7, "Security:\n- API keys in .env (not in Git)\n- Consent-based data access\n- Audit logging with hash chains\n\nCompliance: 96.4%\n- DIGIPIN Specs: 10/10\n- Confidence Score: 12/12\n- Validation Workflow: 8/8\n- Database Schema: 7/7\n- API/UI: 12/12\n- Security: 4/6")

# Final page
pdf.add_page()
pdf.ln(50)
pdf.set_font('Helvetica', 'B', 20)
pdf.set_text_color(102, 126, 234)
pdf.cell(0, 15, 'Thank You', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(10)
pdf.set_font('Helvetica', '', 14)
pdf.set_text_color(0, 0, 0)
pdf.cell(0, 8, 'AAVA - Authorised Address Validation Agency', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(20)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(128, 128, 128)
pdf.cell(0, 8, 'GitHub: https://github.com/Razz0711/AAVA', new_x="LMARGIN", new_y="NEXT", align='C')

pdf.output('AAVA_Documentation.pdf')
print("PDF generated: AAVA_Documentation.pdf")
